import headerCSS from "./header.css";
import git from "../img/githubimg";
const header = document.createElement("section");
header.setAttribute("id", "header");
const portrait = document.createElement("a");
portrait.setAttribute("id", "portrait");
portrait.href = "https://github.com/TCdotmake/todolist";
portrait.target = "_blank";
const rect = document.createElement("div");
rect.setAttribute("id", "rect");
const title = document.createElement("h2");
title.innerHTML = "EZ Todo";
const sub = document.createElement("p");
sub.innerHTML = "set it, do it, done";
rect.append(title, sub);
header.appendChild(portrait);
header.appendChild(rect);
portrait.append(git);
export default header;
