const data = {
  children: [
    {
      name: "General",
      expand: false,
      children: [
        {
          name: "Get Ann a birthday card",
          desc: "",
          due: "2023-12-12",
          priority: "High",
          complete: false,
          pinned: true,
          children: [],
          id: "0af641c3e6f",
          filter: "all",
          parentID: "6cc8ab5f69d",
        },
        {
          name: "Get dog food",
          desc: "",
          due: "2023-12-05",
          priority: "Med",
          complete: true,
          pinned: false,
          children: [],
          id: "af641c3e6fb",
          filter: "all",
          parentID: "6cc8ab5f69d",
        },
      ],
      id: "6cc8ab5f69d",
      parentID: "d6cc8ab5f69",
    },
    {
      name: "Shopping List",
      expand: false,
      children: [
        {
          name: "milk",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "63096e1b5bc",
          filter: "all",
          parentID: "663096e1b5b",
        },
        {
          name: "onion",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "3096e1b5bca",
          filter: "all",
          parentID: "663096e1b5b",
        },
        {
          name: "ground beef",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "096e1b5bca0",
          filter: "all",
          parentID: "663096e1b5b",
        },
        {
          name: "garlic",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "96e1b5bca02",
          filter: "all",
          parentID: "663096e1b5b",
        },
        {
          name: "cornbread mix",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "6e1b5bca021",
          filter: "all",
          parentID: "663096e1b5b",
        },
        {
          name: "chili powder",
          desc: "",
          due: "",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "e1b5bca0212",
          filter: "all",
          parentID: "663096e1b5b",
        },
      ],
      id: "663096e1b5b",
      filter: "all",
      parentID: "d6cc8ab5f69",
    },
    {
      name: "Vacation 2025",
      expand: false,
      children: [
        {
          name: "Scout destination",
          desc: "",
          due: "2025-01-10",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "3e6fb4dc355",
          filter: "all",
          parentID: "c3e6fb4dc35",
        },
        {
          name: "reserve hotel",
          desc: "",
          due: "2025-02-03",
          priority: "Med",
          complete: false,
          pinned: false,
          children: [],
          id: "e6fb4dc355e",
          filter: "all",
          parentID: "c3e6fb4dc35",
        },
        {
          name: "get tickets",
          desc: "",
          due: "2025-02-04",
          priority: "Low",
          complete: false,
          pinned: false,
          children: [],
          id: "6fb4dc355e5",
          filter: "all",
          parentID: "c3e6fb4dc35",
        },
      ],
      id: "c3e6fb4dc35",
      filter: "all",
      parentID: "d6cc8ab5f69",
    },
  ],
  id: "d6cc8ab5f69",
  filters: {},
  filter: "all",
  filteredItems: null,
  filterExpand: true,
};

export default data;
